export const UPDATE_SELECT_MARITAL_STATUS = "UPDATE_SELECT_MARITAL_STATUS";
export const SELECT_MARITAL_STATUS = "SELECT_MARITAL_STATUS";
export const SHOW_SELECT_DATE_PICKER = "SHOW_SELECT_DATE_PICKER";
export const GET_MARITAL_STATUS_ITEMS = "GET_MARITAL_STATUS_ITEMS";
export const SHOW_SELECT_MARITAL_OPTIONS = "SHOW_SELECT_MARITAL_OPTIONS";
export const SELECT_DATE_PICKER = "SELECT_DATE_PICKER";